name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Restore
      run: dotnet restore
    - name: Build Parbad.Sample.EntityFrameworkCore
      run: dotnet build Storage\Parbad.Sample.EntityFrameworkCore\Parbad.Sample.EntityFrameworkCore.csproj
    - name: Build the Docker image
      run: |
        cd Web/Parbad.Sample.Docker
        docker build . -t ssoltani/parbad.samples.aspnetcore
